### ISSUE TITLE
Defer loading of CSS and Javascript files

### ISSUE THREAD

**Issue by Beholder1984** [Superbeest/Core#5]
For CSS and Javascript optimization it is necessary to defer the loading of Javascript and CSS files as described in https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery
My suggestion is to add an extra parameter to the functions
public function addCSSFile(\SimpleXMLElement $xml, $localFile, $remoteFile, $media = \System\Web\BasePage\Page\BasePage::CSS_MEDIA_SCREEN, $rel = \System\Web\BasePage\Page\BasePage::CSS_REL_DEFAULT)
and
public function addJSFile(\SimpleXMLElement $xml, $localFile, $remoteFile)
Which describes where to load the file: in the header or after the html close tag.

**Comment by Superbeest** [comment]
Fixed in 49541cf
