### ISSUE TITLE
Image effects are broken

### ISSUE THREAD

**Issue by Beholder1984** [Superbeest/Core#6]
The image effects \System\Image\Effect\ReflectionEffect and \System\Image\Effect\ShadowEffect are broken if you use Imagick version 3.1.0 or above which was released 3 years ago. 
In these effects the function Imagick::clone is used which is deprecated.
"This function has been DEPRECATED as of imagick 3.1.0 in favour of using the clone keyword."

**Comment by Superbeest** [comment]
fixed with  778dd4c
